### PR TITLE
Export variables for Wayland in zsh profile

### PR DESCRIPTION
**Pull request by ventureoo**
Some users notice that environment variables for Wayland don't work when running applications from their desktop environment (Plasma/GNOME mostly). Exporting variables in a profile should fix this issue.

### CODE REVIEW

**Comment by vnepogodin** [comment]
Well that doesn't change anything

**Comment by vnepogodin** [comment]
It should be either in `~/.zprofile` or `~/.zshenv`.

**Comment by ventureoo** [comment]
> @ventureoo Hmm I think we should put it to ~/.zshenv anyways, because ~/.zprofile and ~/.zshrc are not always sourced
> 
> > .zprofile : will be sourced before .zshrc. Note that, both .zprofile and .zshrc are skipped in non-login non-interactive shells.

Done. btw PKGBUILD in this repository isn't used as I understand?

**Comment by ptr1337** [comment]
> > @ventureoo Hmm I think we should put it to ~/.zshenv anyways, because ~/.zprofile and ~/.zshrc are not always sourced
> > > .zprofile : will be sourced before .zshrc. Note that, both .zprofile and .zshrc are skipped in non-login non-interactive shells.
> 
> Done. btw PKGBUILD in this repository isn't used as I understand?

I think we should move them to one repo, like in CachyOS-PKGBUILDs.
Maybe doing this in a separate PR.

**Comment by vnepogodin** [comment]
> > @ventureoo Hmm I think we should put it to ~/.zshenv anyways, because ~/.zprofile and ~/.zshrc are not always sourced
> > > .zprofile : will be sourced before .zshrc. Note that, both .zprofile and .zshrc are skipped in non-login non-interactive shells.
> 
> Done. btw PKGBUILD in this repository isn't used as I understand?

thank you.

no. PKGBUILD in that repository is abandoned. we can simply remove it

**Pull request merged**
